# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d2dddb7452fabc2dcc83177a3ad2f7abdc6a2ec958ba4baa0b2bed7cdebf58d799590f50ad44d4fa549589f43077a684b39152e15966f12b08e54ea7ee7577

test:
  secret_key_base: c6bfd75a3e860540220c08e5c859648e6a3b6617c5d5a1846c463731b093de9d855c177f43e24fda546a5a55e549dd689b4be26b40213a1a2679efcc73faf504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
